version: '3.8'

services:
  some-postgres:
    image: postgres:latest
    restart: always
    environment:
      TZ: "UTC"
      PGTZ: "UTC"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql
    container_name: some-postgres